"""
# =========================================================================
# Graph Machine Learning & GNN Classifier for Attack Detection
# Based on Causal & Provenance Graphs Generated by UTLParser
# Supports:
#  1. GNN (Graph Convolutional Network - GCN) via PyTorch
#  2. Random Forest Classifier via Scikit-Learn (Baseline)
# =========================================================================
"""

import sys
from pathlib import Path
parent_dir = Path(__file__).resolve().parent.parent.as_posix()
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

import argparse
import logging
import time
import ipaddress
import numpy as np
import scipy.sparse as sp
import networkx as nx
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, f1_score, precision_score, recall_score, accuracy_score
from sklearn.utils.class_weight import compute_class_weight

try:
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
    HAS_TORCH = True
except ImportError:
    HAS_TORCH = False

import cfg

logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s]: %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
logger = logging.getLogger("TrainGNN")


# =========================================================================
# 1. Feature Extraction & Graph Processing
# =========================================================================

def is_private_ip(ip_str):
    try:
        ip = ipaddress.ip_address(ip_str.split(':')[0])
        return 1.0 if ip.is_private else 0.0
    except ValueError:
        return 0.0

def is_ip(s):
    try:
        ipaddress.ip_address(s.split(':')[0])
        return 1.0
    except ValueError:
        return 0.0

FEATURE_NAMES = [
    "in_degree",
    "out_degree",
    "total_degree",
    "in_out_ratio",
    "is_ip_address",
    "is_private_ip",
    "avg_neighbor_degree",
    "neighbor_count"
]

def extract_node_features_and_labels(G, max_nodes=None, propagate_neighbors=True):
    """
    Extracts informative structural and attribute features for every node in G,
    and assigns binary labels (1: Malicious / Incident, 0: Benign) based on IoCs.
    """
    logger.info("Extracting node features and labels from graph...")
    
    # Subsample if graph exceeds max_nodes to allow fast training/experimentation
    if max_nodes and G.number_of_nodes() > max_nodes:
        logger.info(f"Subsampling top {max_nodes} most connected nodes from {G.number_of_nodes()} total nodes...")
        sorted_nodes = sorted(G.degree(), key=lambda x: x[1], reverse=True)[:max_nodes]
        G = G.subgraph([n for n, _ in sorted_nodes]).copy()

    # Collect known IoCs from config
    malicious_ips = set(cfg.ait_iot_dict.get("Src_IP", []) + cfg.iot_ioc_dict.get("Dest_IP", []))
    malicious_iocs = set(str(x) for x in cfg.ait_iot_dict.get("IOCs", []) + cfg.iot_ioc_dict.get("IOCs", []))
    malicious_actions = set(cfg.ait_iot_dict.get("Actions", []))

    # Identify primary attacker / IoC nodes
    attack_nodes = set()
    for node in G.nodes():
        node_str = str(node)
        if node_str in malicious_ips or node_str in malicious_iocs:
            attack_nodes.add(node)
        else:
            for val in G.nodes[node].values():
                if str(val) in malicious_iocs or str(val) in malicious_ips:
                    attack_nodes.add(node)
                    break

    # Propagate attack incident labels to directly connected victim hosts / targeted services
    incident_nodes = set(attack_nodes)
    if propagate_neighbors and attack_nodes:
        for u, v, edata in G.edges(data=True):
            if u in attack_nodes or v in attack_nodes:
                incident_nodes.add(u)
                incident_nodes.add(v)
            else:
                action = str(edata.get("value", ""))
                ioc_val = str(edata.get("IOCs", ""))
                if action in malicious_actions or ioc_val in malicious_iocs:
                    incident_nodes.add(u)
                    incident_nodes.add(v)

    node_list = list(G.nodes())
    num_nodes = len(node_list)

    in_degrees = dict(G.in_degree()) if G.is_directed() else dict(G.degree())
    out_degrees = dict(G.out_degree()) if G.is_directed() else dict(G.degree())
    total_degrees = dict(G.degree())

    features = []
    labels = []
    malicious_count = 0

    for node in node_list:
        node_str = str(node)
        in_deg = float(in_degrees.get(node, 0))
        out_deg = float(out_degrees.get(node, 0))
        tot_deg = float(total_degrees.get(node, 0))
        ratio = in_deg / (out_deg + 1.0)

        is_ip_val = is_ip(node_str)
        is_priv_val = is_private_ip(node_str) if is_ip_val else 0.0

        neighbors = list(G.neighbors(node))
        n_count = len(neighbors)
        avg_neighbor_deg = float(np.mean([total_degrees.get(nbr, 0) for nbr in neighbors])) if n_count > 0 else 0.0

        feat = [
            in_deg,
            out_deg,
            tot_deg,
            ratio,
            is_ip_val,
            is_priv_val,
            avg_neighbor_deg,
            float(n_count)
        ]
        features.append(feat)

        is_malicious = 1 if node in incident_nodes else 0
        if is_malicious:
            malicious_count += 1
        labels.append(is_malicious)

    logger.info(f"Total Nodes: {num_nodes} | Malicious / Incident (Class 1): {malicious_count} ({malicious_count/num_nodes*100:.2f}%) | Benign (Class 0): {num_nodes - malicious_count}")

    # Fallback heuristic if 0 direct IoCs matched in small sample
    if malicious_count == 0:
        logger.warning("No direct IoC matched in current sample. Tagging top 5% highest out-degree nodes (potential scanners) as anomalous for training baseline.")
        top_k = max(1, int(num_nodes * 0.05))
        top_anom = sorted(range(num_nodes), key=lambda i: features[i][1], reverse=True)[:top_k]
        for idx in top_anom:
            labels[idx] = 1

    # Standardize features
    scaler = StandardScaler()
    X = scaler.fit_transform(np.array(features, dtype=np.float32))
    Y = np.array(labels, dtype=np.int64)

    # Build Adjacency Matrix
    adj = nx.adjacency_matrix(G, nodelist=node_list)
    if G.is_directed():
        adj = adj + adj.T.multiply(adj.T > adj) - adj.multiply(adj.T > adj)

    return X, Y, adj, node_list


def stratified_split(Y_np, train_ratio=0.70, val_ratio=0.15):
    """Guarantees positive samples are distributed across Train, Val, and Test splits."""
    pos_idx = np.where(Y_np == 1)[0]
    neg_idx = np.where(Y_np == 0)[0]
    np.random.shuffle(pos_idx)
    np.random.shuffle(neg_idx)
    
    n_pos = len(pos_idx)
    n_neg = len(neg_idx)
    
    if n_pos >= 3:
        n_pos_train = max(1, int(train_ratio * n_pos))
        n_pos_val = max(1, int(val_ratio * n_pos))
        pos_train = pos_idx[:n_pos_train]
        pos_val = pos_idx[n_pos_train:n_pos_train + n_pos_val]
        pos_test = pos_idx[n_pos_train + n_pos_val:]
        if len(pos_test) == 0:
            pos_test = pos_val
    elif n_pos == 2:
        pos_train = pos_idx[:1]
        pos_val = pos_idx[1:2]
        pos_test = pos_idx[1:2]
    else:
        pos_train = pos_idx
        pos_val = pos_idx
        pos_test = pos_idx

    n_neg_train = int(train_ratio * n_neg)
    n_neg_val = int(val_ratio * n_neg)
    neg_train = neg_idx[:n_neg_train]
    neg_val = neg_idx[n_neg_train:n_neg_train + n_neg_val]
    neg_test = neg_idx[n_neg_train + n_neg_val:]

    train_idx = np.concatenate([pos_train, neg_train])
    val_idx = np.concatenate([pos_val, neg_val])
    test_idx = np.concatenate([pos_test, neg_test])
    
    np.random.shuffle(train_idx)
    np.random.shuffle(val_idx)
    np.random.shuffle(test_idx)
    return train_idx, val_idx, test_idx


def normalize_adj(adj):
    """Symmetric normalization D^(-1/2) * (A + I) * D^(-1/2)"""
    adj = adj + sp.eye(adj.shape[0])
    rowsum = np.array(adj.sum(1))
    d_inv_sqrt = np.power(rowsum, -0.5).flatten()
    d_inv_sqrt[np.isinf(d_inv_sqrt)] = 0.
    d_mat_inv_sqrt = sp.diags(d_inv_sqrt)
    normalized = adj.dot(d_mat_inv_sqrt).transpose().dot(d_mat_inv_sqrt).tocoo()

    indices = torch.from_numpy(np.vstack((normalized.row, normalized.col)).astype(np.int64))
    values = torch.from_numpy(normalized.data.astype(np.float32))
    shape = torch.Size(normalized.shape)
    return torch.sparse_coo_tensor(indices, values, shape)


# =========================================================================
# 2. PyTorch GNN (GCN) Architecture
# =========================================================================

if HAS_TORCH:
    class GCNLayer(nn.Module):
        def __init__(self, in_features, out_features):
            super().__init__()
            self.linear = nn.Linear(in_features, out_features, bias=True)
            nn.init.xavier_uniform_(self.linear.weight)

        def forward(self, x, adj_norm):
            support = self.linear(x)
            out = torch.sparse.mm(adj_norm, support)
            return out


    class GCNIntrusionDetector(nn.Module):
        def __init__(self, in_features, hidden_dim=64, num_classes=2, dropout=0.3):
            super().__init__()
            self.conv1 = GCNLayer(in_features, hidden_dim)
            self.bn1 = nn.BatchNorm1d(hidden_dim)
            self.conv2 = GCNLayer(hidden_dim, hidden_dim)
            self.bn2 = nn.BatchNorm1d(hidden_dim)
            self.classifier = nn.Linear(hidden_dim, num_classes)
            self.dropout = nn.Dropout(dropout)

        def forward(self, x, adj_norm):
            h = self.conv1(x, adj_norm)
            h = self.bn1(h)
            h = F.relu(h)
            h = self.dropout(h)

            h = self.conv2(h, adj_norm)
            h = self.bn2(h)
            h = F.relu(h)
            h = self.dropout(h)

            out = self.classifier(h)
            return out


# =========================================================================
# 3. Model Training Functions
# =========================================================================

def train_rf_baseline(X_train, Y_train, X_test, Y_test, output_dir):
    from sklearn.ensemble import RandomForestClassifier
    logger.info("Training Random Forest Classifier on graph structural features...")
    clf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
    clf.fit(X_train, Y_train)
    test_preds = clf.predict(X_test)

    acc = accuracy_score(Y_test, test_preds)
    prec = precision_score(Y_test, test_preds, zero_division=0)
    rec = recall_score(Y_test, test_preds, zero_division=0)
    f1 = f1_score(Y_test, test_preds, zero_division=0)

    print("\n" + "="*50)
    print("--- Test Metrics (Random Forest) ---")
    print("="*50)
    print(f"Accuracy  : {acc * 100:.2f}%")
    print(f"Precision : {prec * 100:.2f}%")
    print(f"Recall    : {rec * 100:.2f}%")
    print(f"F1-Score  : {f1 * 100:.2f}%\n")

    print("--- Detailed Classification Report ---")
    print(classification_report(Y_test, test_preds, target_names=["Benign (0)", "Attack (1)"], zero_division=0))

    print("--- Confusion Matrix ---")
    cm = confusion_matrix(Y_test, test_preds)
    print(f"TN: {cm[0,0]} | FP: {cm[0,1]}")
    print(f"FN: {cm[1,0]} | TP: {cm[1,1]}\n")

    print("--- Most Discriminative Graph Features ---")
    for name, imp in sorted(zip(FEATURE_NAMES, clf.feature_importances_), key=lambda x: x[1], reverse=True):
        print(f" - {name:<22}: {imp * 100:.2f}%")

    try:
        import joblib
        save_path = Path(output_dir).joinpath("rf_graph_model.joblib")
        joblib.dump(clf, save_path)
        logger.info(f"Model saved to: {save_path}")
    except Exception:
        pass


def train_gnn_model(args, X_np, Y_np, adj_sp, train_idx, val_idx, test_idx):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger.info(f"Using device: {device}")

    adj_norm = normalize_adj(adj_sp).to(device)
    X = torch.tensor(X_np, dtype=torch.float32).to(device)
    Y = torch.tensor(Y_np, dtype=torch.long).to(device)

    train_idx_t = torch.tensor(train_idx, dtype=torch.long).to(device)
    val_idx_t = torch.tensor(val_idx, dtype=torch.long).to(device)
    test_idx_t = torch.tensor(test_idx, dtype=torch.long).to(device)

    # Safe class weights computation
    train_classes = np.unique(Y_np[train_idx])
    if len(train_classes) < 2:
        weight_tensor = torch.tensor([1.0, 1.0], dtype=torch.float32).to(device)
    else:
        class_weights = compute_class_weight(class_weight="balanced", classes=np.array([0, 1]), y=Y_np[train_idx])
        weight_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)
    
    criterion = nn.CrossEntropyLoss(weight=weight_tensor)

    in_features = X.shape[1]
    model = GCNIntrusionDetector(in_features=in_features, hidden_dim=args.hidden_dim, num_classes=2, dropout=args.dropout).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.learning_rate, weight_decay=args.weight_decay)

    logger.info("Starting GNN training...")
    best_val_f1 = 0.0
    best_model_weights = None

    for epoch in range(1, args.epochs + 1):
        t0 = time.time()
        model.train()
        optimizer.zero_grad()
        logits = model(X, adj_norm)
        loss = criterion(logits[train_idx_t], Y[train_idx_t])
        loss.backward()
        optimizer.step()

        # Validation
        model.eval()
        with torch.no_grad():
            val_logits = model(X, adj_norm)
            val_preds = torch.argmax(val_logits[val_idx_t], dim=1).cpu().numpy()
            val_targets = Y[val_idx_t].cpu().numpy()

            val_acc = accuracy_score(val_targets, val_preds)
            val_f1 = f1_score(val_targets, val_preds, zero_division=0)

            if val_f1 > best_val_f1:
                best_val_f1 = val_f1
                best_model_weights = model.state_dict().copy()

        if epoch % 5 == 0 or epoch == args.epochs:
            logger.info(
                f"Epoch [{epoch:03d}/{args.epochs:03d}] | "
                f"Loss: {loss.item():.4f} | "
                f"Val Acc: {val_acc:.4f} | "
                f"Val F1: {val_f1:.4f} | "
                f"Time: {time.time() - t0:.2f}s"
            )

    logger.info("="*50)
    logger.info("Evaluating Best GNN Model on Unseen Test Set:")
    logger.info("="*50)
    if best_model_weights:
        model.load_state_dict(best_model_weights)

    model.eval()
    with torch.no_grad():
        test_logits = model(X, adj_norm)
        test_preds = torch.argmax(test_logits[test_idx_t], dim=1).cpu().numpy()
        test_targets = Y[test_idx_t].cpu().numpy()

    acc = accuracy_score(test_targets, test_preds)
    prec = precision_score(test_targets, test_preds, zero_division=0)
    rec = recall_score(test_targets, test_preds, zero_division=0)
    f1 = f1_score(test_targets, test_preds, zero_division=0)

    print("\n--- Test Metrics (GNN / GCN) ---")
    print(f"Accuracy  : {acc * 100:.2f}%")
    print(f"Precision : {prec * 100:.2f}%")
    print(f"Recall    : {rec * 100:.2f}%")
    print(f"F1-Score  : {f1 * 100:.2f}%\n")

    print("--- Detailed Classification Report ---")
    print(classification_report(test_targets, test_preds, target_names=["Benign (0)", "Attack (1)"], zero_division=0))

    print("--- Confusion Matrix ---")
    cm = confusion_matrix(test_targets, test_preds)
    print(f"TN: {cm[0,0]} | FP: {cm[0,1]}")
    print(f"FN: {cm[1,0]} | TP: {cm[1,1]}\n")

    save_dir = Path(args.output)
    save_dir.mkdir(parents=True, exist_ok=True)
    model_save_path = save_dir.joinpath("gnn_model.pt")
    torch.save(model.state_dict(), model_save_path)
    logger.info(f"Trained GNN model saved to: {model_save_path}")


# =========================================================================
# 4. Entrypoint
# =========================================================================

def main():
    parser = argparse.ArgumentParser(description="Train Graph Machine Learning / GNN model on UTLParser Causal Graphs")
    parser.add_argument("-g", "--graph", type=str, default="../output/full.graphml", help="Path to input .graphml file")
    parser.add_argument("-o", "--output", type=str, default="../output", help="Directory to save trained model")
    parser.add_argument("-m", "--model", type=str, choices=["gnn", "rf"], default="gnn" if HAS_TORCH else "rf",
                        help="Model architecture: 'gnn' (Graph Convolutional Network via PyTorch) or 'rf' (Random Forest via Scikit-Learn)")
    parser.add_argument("-e", "--epochs", type=int, default=50, help="Number of GNN training epochs (default: 50)")
    parser.add_argument("-lr", "--learning_rate", type=float, default=0.01, help="Adam learning rate (default: 0.01)")
    parser.add_argument("-d", "--hidden_dim", type=int, default=64, help="GCN hidden dimension (default: 64)")
    parser.add_argument("--dropout", type=float, default=0.3, help="Dropout rate (default: 0.3)")
    parser.add_argument("--weight_decay", type=float, default=5e-4, help="L2 regularization (default: 5e-4)")
    parser.add_argument("--max_nodes", type=int, default=100000, help="Max nodes to sample for fast training if graph is massive (default: 100000)")
    parser.add_argument("--no_propagate", action="store_true", help="Disable incident propagation to victim neighbors")

    args = parser.parse_args()

    if args.model == "gnn" and not HAS_TORCH:
        logger.error(
            "\n" + "="*65 + "\n"
            "AVISO: O pacote 'torch' (PyTorch) não está instalado!\n\n"
            "Para treinar a Rede Neural em Grafos (GNN), instale com:\n"
            "    pip install torch\n\n"
            "Ou, para treinar AGORA MESMO sem PyTorch usando Random Forest:\n"
            "    python3 train_gnn.py -m rf\n"
            + "="*65
        )
        sys.exit(1)

    # 1. Resolve GraphML path
    graph_path = Path(args.graph)
    if not graph_path.exists():
        candidates = [
            Path(args.output).joinpath("full.graphml"),
            Path(args.output).joinpath("conn.graphml"),
            Path(args.output).joinpath("dns.graphml"),
        ]
        for c in candidates:
            if c.exists():
                graph_path = c
                break

    if not graph_path.exists():
        raise FileNotFoundError(f"Could not find graph file at '{args.graph}'. Make sure to run main.py first.")

    logger.info(f"Loading GraphML from: {graph_path}")
    G = nx.read_graphml(graph_path)
    logger.info(f"Graph loaded successfully with {G.number_of_nodes()} nodes and {G.number_of_edges()} edges.")

    # 2. Extract features and labels
    propagate = not args.no_propagate
    X_np, Y_np, adj_sp, node_list = extract_node_features_and_labels(G, max_nodes=args.max_nodes, propagate_neighbors=propagate)

    # Stratified split to ensure both classes exist in Train, Val and Test sets
    train_idx, val_idx, test_idx = stratified_split(Y_np, train_ratio=0.70, val_ratio=0.15)

    logger.info(f"Stratified Dataset split: Train={len(train_idx)} | Val={len(val_idx)} | Test={len(test_idx)}")

    if args.model == "rf":
        train_rf_baseline(X_np[train_idx], Y_np[train_idx], X_np[test_idx], Y_np[test_idx], args.output)
    else:
        train_gnn_model(args, X_np, Y_np, adj_sp, train_idx, val_idx, test_idx)


if __name__ == "__main__":
    main()
