"""
# =========================================================================
# GNN (Graph Neural Network) Classifier for Intrusion & Attack Detection
# Based on Causal & Provenance Graphs Generated by UTLParser
# =========================================================================
"""

import sys
from pathlib import Path
parent_dir = Path(__file__).resolve().parent.parent.as_posix()
if parent_dir not in sys.path:
    sys.path.insert(0, parent_dir)

import argparse
import logging
import time
import re
import ipaddress
import numpy as np
import scipy.sparse as sp
import networkx as nx
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, f1_score, precision_score, recall_score, accuracy_score
from sklearn.utils.class_weight import compute_class_weight

import cfg

logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s]: %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
logger = logging.getLogger("TrainGNN")


# =========================================================================
# 1. Feature Extraction & Graph Processing
# =========================================================================

def is_private_ip(ip_str):
    try:
        ip = ipaddress.ip_address(ip_str.split(':')[0])
        return 1.0 if ip.is_private else 0.0
    except ValueError:
        return 0.0

def is_ip(s):
    try:
        ipaddress.ip_address(s.split(':')[0])
        return 1.0
    except ValueError:
        return 0.0

def extract_node_features_and_labels(G, max_nodes=None):
    """
    Extracts informative structural and attribute features for every node in G,
    and assigns binary labels (1: Malicious / Attack, 0: Benign) based on IoCs.
    """
    logger.info("Extracting node features and labels from graph...")
    
    # Subsample if graph exceeds max_nodes to allow fast training/experimentation
    if max_nodes and G.number_of_nodes() > max_nodes:
        logger.info(f"Subsampling top {max_nodes} most connected nodes from {G.number_of_nodes()} total nodes...")
        sorted_nodes = sorted(G.degree(), key=lambda x: x[1], reverse=True)[:max_nodes]
        G = G.subgraph([n for n, _ in sorted_nodes]).copy()

    # Collect known IoCs from config
    malicious_ips = set(cfg.ait_iot_dict.get("Src_IP", []) + cfg.iot_ioc_dict.get("Dest_IP", []))
    malicious_iocs = set(str(x) for x in cfg.ait_iot_dict.get("IOCs", []) + cfg.iot_ioc_dict.get("IOCs", []))
    malicious_actions = set(cfg.ait_iot_dict.get("Actions", []))

    node_list = list(G.nodes())
    node_to_idx = {node: i for i, node in enumerate(node_list)}
    num_nodes = len(node_list)

    # In-degree, Out-degree dictionaries
    in_degrees = dict(G.in_degree()) if G.is_directed() else dict(G.degree())
    out_degrees = dict(G.out_degree()) if G.is_directed() else dict(G.degree())
    total_degrees = dict(G.degree())

    features = []
    labels = []
    malicious_count = 0

    for node in node_list:
        node_str = str(node)
        in_deg = float(in_degrees.get(node, 0))
        out_deg = float(out_degrees.get(node, 0))
        tot_deg = float(total_degrees.get(node, 0))
        ratio = in_deg / (out_deg + 1.0)

        is_ip_val = is_ip(node_str)
        is_priv_val = is_private_ip(node_str) if is_ip_val else 0.0

        # Neighbors feature aggregation
        neighbors = list(G.neighbors(node))
        n_count = len(neighbors)
        avg_neighbor_deg = float(np.mean([total_degrees.get(nbr, 0) for nbr in neighbors])) if n_count > 0 else 0.0

        feat = [
            in_deg,
            out_deg,
            tot_deg,
            ratio,
            is_ip_val,
            is_priv_val,
            avg_neighbor_deg,
            float(n_count)
        ]
        features.append(feat)

        # Ground truth label assignment based on IoC rules
        is_malicious = 0
        if node_str in malicious_ips or node_str in malicious_iocs:
            is_malicious = 1
        else:
            # Check node attributes or adjacent edge attributes
            node_data = G.nodes[node]
            for val in node_data.values():
                if str(val) in malicious_iocs:
                    is_malicious = 1
                    break
            
            if not is_malicious:
                # Check connected edges for attack actions
                if G.is_directed():
                    edges_data = G.in_edges(node, data=True)
                else:
                    edges_data = G.edges(node, data=True)
                for _, _, edata in edges_data:
                    action = edata.get("value", "")
                    if action in malicious_actions or str(edata.get("IOCs", "")) in malicious_iocs:
                        is_malicious = 1
                        break

        if is_malicious:
            malicious_count += 1
        labels.append(is_malicious)

    logger.info(f"Total Nodes: {num_nodes} | Malicious (Class 1): {malicious_count} ({malicious_count/num_nodes*100:.2f}%) | Benign (Class 0): {num_nodes - malicious_count}")

    # Fallback synthetic perturbation if 0 malicious found (ensures model can train and test cleanly)
    if malicious_count == 0:
        logger.warning("No direct IoC matched in current sample. Tagging top 5% highest out-degree nodes (potential scanners) as anomalous for training baseline.")
        top_k = max(1, int(num_nodes * 0.05))
        top_anom = sorted(range(num_nodes), key=lambda i: features[i][1], reverse=True)[:top_k]
        for idx in top_anom:
            labels[idx] = 1

    # Standardize features
    scaler = StandardScaler()
    X = scaler.fit_transform(np.array(features, dtype=np.float32))
    Y = np.array(labels, dtype=np.int64)

    # Build Adjacency Matrix
    adj = nx.adjacency_matrix(G, nodelist=node_list)
    # Make symmetric if directed for undirected message passing
    if G.is_directed():
        adj = adj + adj.T.multiply(adj.T > adj) - adj.multiply(adj.T > adj)

    return X, Y, adj, node_list


def normalize_adj(adj):
    """Symmetric normalization D^(-1/2) * (A + I) * D^(-1/2)"""
    adj = adj + sp.eye(adj.shape[0])
    rowsum = np.array(adj.sum(1))
    d_inv_sqrt = np.power(rowsum, -0.5).flatten()
    d_inv_sqrt[np.isinf(d_inv_sqrt)] = 0.
    d_mat_inv_sqrt = sp.diags(d_inv_sqrt)
    normalized = adj.dot(d_mat_inv_sqrt).transpose().dot(d_mat_inv_sqrt).tocoo()

    # Convert to PyTorch sparse tensor
    indices = torch.from_numpy(np.vstack((normalized.row, normalized.col)).astype(np.int64))
    values = torch.from_numpy(normalized.data.astype(np.float32))
    shape = torch.Size(normalized.shape)
    return torch.sparse_coo_tensor(indices, values, shape)


# =========================================================================
# 2. Graph Convolutional Network (GCN) Architecture in Pure PyTorch
# =========================================================================

class GCNLayer(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.linear = nn.Linear(in_features, out_features, bias=True)
        nn.init.xavier_uniform_(self.linear.weight)

    def forward(self, x, adj_norm):
        support = self.linear(x)
        out = torch.sparse.mm(adj_norm, support)
        return out


class GCNIntrusionDetector(nn.Module):
    def __init__(self, in_features, hidden_dim=64, num_classes=2, dropout=0.3):
        super().__init__()
        self.conv1 = GCNLayer(in_features, hidden_dim)
        self.bn1 = nn.BatchNorm1d(hidden_dim)
        self.conv2 = GCNLayer(hidden_dim, hidden_dim)
        self.bn2 = nn.BatchNorm1d(hidden_dim)
        self.classifier = nn.Linear(hidden_dim, num_classes)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, adj_norm):
        h = self.conv1(x, adj_norm)
        h = self.bn1(h)
        h = F.relu(h)
        h = self.dropout(h)

        h = self.conv2(h, adj_norm)
        h = self.bn2(h)
        h = F.relu(h)
        h = self.dropout(h)

        out = self.classifier(h)
        return out


# =========================================================================
# 3. Training & Evaluation Pipeline
# =========================================================================

def train_gnn(args):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger.info(f"Using device: {device}")

    # 1. Resolve GraphML path
    graph_path = Path(args.graph)
    if not graph_path.exists():
        candidates = [
            Path(args.output).joinpath("full.graphml"),
            Path(args.output).joinpath("conn.graphml"),
            Path(args.output).joinpath("dns.graphml"),
        ]
        for c in candidates:
            if c.exists():
                graph_path = c
                break

    if not graph_path.exists():
        raise FileNotFoundError(f"Could not find graph file at '{args.graph}'. Make sure to run main.py first.")

    logger.info(f"Loading GraphML from: {graph_path}")
    G = nx.read_graphml(graph_path)
    logger.info(f"Graph loaded successfully with {G.number_of_nodes()} nodes and {G.number_of_edges()} edges.")

    # 2. Extract features, labels, and normalized adjacency
    X_np, Y_np, adj_sp, node_list = extract_node_features_and_labels(G, max_nodes=args.max_nodes)
    adj_norm = normalize_adj(adj_sp).to(device)
    X = torch.tensor(X_np, dtype=torch.float32).to(device)
    Y = torch.tensor(Y_np, dtype=torch.long).to(device)

    num_nodes = len(Y_np)
    indices = np.random.permutation(num_nodes)
    train_end = int(0.70 * num_nodes)
    val_end = int(0.85 * num_nodes)

    train_idx = torch.tensor(indices[:train_end], dtype=torch.long).to(device)
    val_idx = torch.tensor(indices[train_end:val_end], dtype=torch.long).to(device)
    test_idx = torch.tensor(indices[val_end:], dtype=torch.long).to(device)

    logger.info(f"Dataset split: Train={len(train_idx)} | Val={len(val_idx)} | Test={len(test_idx)}")

    # Class balancing weights
    classes = np.unique(Y_np)
    class_weights = compute_class_weight(class_weight="balanced", classes=classes, y=Y_np[indices[:train_end]])
    weight_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)
    criterion = nn.CrossEntropyLoss(weight=weight_tensor)

    # Initialize Model
    in_features = X.shape[1]
    model = GCNIntrusionDetector(in_features=in_features, hidden_dim=args.hidden_dim, num_classes=2, dropout=args.dropout).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.learning_rate, weight_decay=args.weight_decay)

    # 3. Training Loop
    logger.info("Starting GNN training...")
    best_val_f1 = 0.0
    best_model_weights = None

    for epoch in range(1, args.epochs + 1):
        t0 = time.time()
        model.train()
        optimizer.zero_grad()
        logits = model(X, adj_norm)
        loss = criterion(logits[train_idx], Y[train_idx])
        loss.backward()
        optimizer.step()

        # Validation
        model.eval()
        with torch.no_grad():
            val_logits = model(X, adj_norm)
            val_preds = torch.argmax(val_logits[val_idx], dim=1).cpu().numpy()
            val_targets = Y[val_idx].cpu().numpy()

            val_acc = accuracy_score(val_targets, val_preds)
            val_f1 = f1_score(val_targets, val_preds, zero_division=0)

            if val_f1 > best_val_f1:
                best_val_f1 = val_f1
                best_model_weights = model.state_dict().copy()

        if epoch % 5 == 0 or epoch == args.epochs:
            logger.info(
                f"Epoch [{epoch:03d}/{args.epochs:03d}] | "
                f"Loss: {loss.item():.4f} | "
                f"Val Acc: {val_acc:.4f} | "
                f"Val F1: {val_f1:.4f} | "
                f"Time: {time.time() - t0:.2f}s"
            )

    # 4. Final Evaluation on Test Set
    logger.info("=========================================================")
    logger.info("Evaluating Best Model on Unseen Test Set:")
    logger.info("=========================================================")
    if best_model_weights:
        model.load_state_dict(best_model_weights)

    model.eval()
    with torch.no_grad():
        test_logits = model(X, adj_norm)
        test_preds = torch.argmax(test_logits[test_idx], dim=1).cpu().numpy()
        test_targets = Y[test_idx].cpu().numpy()

    acc = accuracy_score(test_targets, test_preds)
    prec = precision_score(test_targets, test_preds, zero_division=0)
    rec = recall_score(test_targets, test_preds, zero_division=0)
    f1 = f1_score(test_targets, test_preds, zero_division=0)

    print("\n--- Test Metrics ---")
    print(f"Accuracy  : {acc * 100:.2f}%")
    print(f"Precision : {prec * 100:.2f}%")
    print(f"Recall    : {rec * 100:.2f}%")
    print(f"F1-Score  : {f1 * 100:.2f}%\n")

    print("--- Detailed Classification Report ---")
    print(classification_report(test_targets, test_preds, target_names=["Benign (0)", "Attack (1)"], zero_division=0))

    print("--- Confusion Matrix ---")
    cm = confusion_matrix(test_targets, test_preds)
    print(f"TN: {cm[0,0]} | FP: {cm[0,1]}")
    print(f"FN: {cm[1,0]} | TP: {cm[1,1]}\n")

    # 5. Save model weights
    save_dir = Path(args.output)
    save_dir.mkdir(parents=True, exist_ok=True)
    model_save_path = save_dir.joinpath("gnn_model.pt")
    torch.save(model.state_dict(), model_save_path)
    logger.info(f"Trained GNN model saved to: {model_save_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train GNN model on UTLParser Causal Graphs for Intrusion Detection")
    parser.add_argument("-g", "--graph", type=str, default="../output/full.graphml", help="Path to input .graphml file")
    parser.add_argument("-o", "--output", type=str, default="../output", help="Directory to save trained model weights")
    parser.add_argument("-e", "--epochs", type=int, default=50, help="Number of training epochs (default: 50)")
    parser.add_argument("-lr", "--learning_rate", type=float, default=0.01, help="Adam learning rate (default: 0.01)")
    parser.add_argument("-d", "--hidden_dim", type=int, default=64, help="GCN hidden dimension (default: 64)")
    parser.add_argument("--dropout", type=float, default=0.3, help="Dropout rate (default: 0.3)")
    parser.add_argument("--weight_decay", type=float, default=5e-4, help="L2 regularization (default: 5e-4)")
    parser.add_argument("--max_nodes", type=int, default=100000, help="Max nodes to sample for fast training if graph is massive (default: 100000)")

    args = parser.parse_args()
    train_gnn(args)
